# Generated by Django 2.0.6 on 2018-08-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
