# Generated by Django 2.0.6 on 2018-08-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180813_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifiants',
            name='lieu',
        ),
    ]
