# Generated by Django 2.0.6 on 2018-07-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifiants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.IntegerField(unique=True)),
                ('noms', models.TextField(blank=True, null=True)),
                ('fiche', models.IntegerField(blank=True, null=True)),
                ('comestible', models.TextField(blank=True, null=True)),
                ('sms', models.NullBooleanField()),
                ('a_imprimer', models.NullBooleanField()),
                ('lieu', models.TextField(blank=True, null=True)),
                ('apparition', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('ecologie', models.TextField(blank=True, null=True)),
                ('icono1', models.TextField(blank=True, null=True)),
                ('icono2', models.TextField(blank=True, null=True)),
                ('icono3', models.TextField(blank=True, null=True)),
                ('num_herbier', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identifiants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesyno', models.SmallIntegerField()),
                ('genre', models.TextField()),
                ('espece', models.TextField()),
                ('variete', models.TextField(blank=True, null=True)),
                ('forme', models.TextField(blank=True, null=True)),
                ('autorite', models.TextField()),
                ('moser', models.TextField()),
                ('biblio1', models.TextField(blank=True, null=True)),
                ('biblio2', models.TextField(blank=True, null=True)),
                ('biblio3', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Identifiants', to_field='taxon')),
            ],
            options={
                'db_table': 'nomenclature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'themes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='identifiants',
            name='theme1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theme1', to='app.Themes', to_field='theme'),
        ),
        migrations.AddField(
            model_name='identifiants',
            name='theme2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theme2', to='app.Themes', to_field='theme'),
        ),
        migrations.AddField(
            model_name='identifiants',
            name='theme3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theme3', to='app.Themes', to_field='theme'),
        ),
        migrations.AddField(
            model_name='identifiants',
            name='theme4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theme4', to='app.Themes', to_field='theme'),
        ),
    ]
