# Generated by Django 2.0.6 on 2018-06-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifiants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.IntegerField(unique=True)),
                ('noms', models.TextField(blank=True, null=True)),
                ('fiche', models.IntegerField(blank=True, null=True)),
                ('comestible', models.TextField(blank=True, null=True)),
                ('sms', models.NullBooleanField()),
                ('a_imprimer', models.NullBooleanField()),
                ('lieu', models.TextField(blank=True, null=True)),
                ('apparition', models.TextField()),
            ],
            options={
                'db_table': 'identifiants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesyno', models.SmallIntegerField()),
                ('genre', models.TextField()),
                ('espece', models.TextField()),
                ('variete', models.TextField(blank=True, null=True)),
                ('forme', models.TextField(blank=True, null=True)),
                ('autorite', models.TextField()),
                ('moser', models.TextField()),
                ('biblio1', models.TextField(blank=True, null=True)),
                ('biblio2', models.TextField(blank=True, null=True)),
                ('biblio3', models.TextField(blank=True, null=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Identifiants', to_field='taxon')),
            ],
            options={
                'db_table': 'nomenclature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotesEco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('ecologie', models.TextField()),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Identifiants', to_field='taxon')),
            ],
            options={
                'db_table': 'notes_eco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.TextField()),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Identifiants', to_field='taxon')),
            ],
            options={
                'db_table': 'themes',
                'managed': True,
            },
        ),
    ]
