# Generated by Django 2.0.6 on 2018-07-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuRecolte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(unique=True)),
                ('commune', models.TextField()),
                ('lieu_dit', models.TextField()),
            ],
            options={
                'db_table': 'lieurec',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListeRecolte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.LieuRecolte')),
            ],
            options={
                'db_table': 'listrec',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='identifiants',
            name='apparition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='autorite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='moser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listerecolte',
            name='taxons',
            field=models.ManyToManyField(to='app.Identifiants'),
        ),
    ]
