# Generated by Django 2.0.6 on 2018-08-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180729_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetRecolte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolteur', models.TextField(blank=True, null=True)),
                ('determinateur', models.TextField(blank=True, null=True)),
                ('num_herbier', models.IntegerField(blank=True, null=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Identifiants')),
            ],
            options={
                'db_table': 'objrec',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='themes',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listerecolte',
            name='taxons',
            field=models.ManyToManyField(to='app.ObjetRecolte'),
        ),
    ]
