# Generated by Django 2.0.6 on 2018-08-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180809_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField()),
                ('regne', models.TextField(blank=True, null=True)),
                ('embranchement', models.TextField(blank=True, null=True)),
                ('classe', models.TextField(blank=True, null=True)),
                ('ordre', models.TextField(blank=True, null=True)),
                ('famille', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classification',
                'managed': True,
            },
        ),
    ]
